import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yoom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        layout:{
          logoImageUrl: "/icons/yoom-logo.svg",
          socialButtonsVariant:"iconButton"
        },
        variables: {
          colorText: "#ffffff",
          colorPrimary: "#0e78F9",
          colorBackground: "#1C1f2e",
          colorInputBackground: "#252a41",
          colorInputText:"#fff"

        }
      }}>
      <body className={` ${inter.className} bg-dark-2`}>
        {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
